### ISSUE TITLE
HNSW reindexing test is indeterministic

### ISSUE THREAD

**Issue by tyb0807** [hicder/muopdb#79]
`hnsw::builder::tests::test_hnsw_builder_reindex` test result is not deterministic: it could be passing, or
```
---- hnsw::builder::tests::test_hnsw_builder_reindex stdout ----
thread 'hnsw::builder::tests::test_hnsw_builder_reindex' panicked at rs/index/src/hnsw/builder.rs:617:13:
assertion `left == right` failed
  left: 102
 right: 100
 ```
 
or even
```
---- hnsw::builder::tests::test_hnsw_builder_reindex stdout ----
thread 'hnsw::builder::tests::test_hnsw_builder_reindex' panicked at rs/index/src/hnsw/builder.rs:617:13:
assertion `left == right` failed
  left: 101
 right: 100
```

**Comment by hicder** [comment]
close by https://github.com/hicder/muopdb/pull/83
